# DeluxeCombatAddon64 v0.0.8-beta by @tbm00
# https://github.com/tbm00/DeluxeCombatAddon64

enabled: true

# Prevents respawn anchor usage if player or nearby players have pvp disabled
fixes:
  anchorExplosionPvpCheck: true

bountyProtectionCommand:
  enabled: true
  saveMapOnPluginDisable: true
  chat:
    prefix: "&8[&f-&8] &f"
    protectionEnabledMessage: "You are now protected from bounties for &a<time_left>&r!"
    currentProtectionTimeMessage: "You are protected from bounties for &a<time_left>&r!"
    noCurrentProtectionMessage: "&cYou are not protected from bounties!"
    cannotSetBountyMessage: "&cThat player is protected from bounties for &6<time_left>&c!"

togglePvpCommand:
  enabled: true
  saveMapOnPluginDisable: true
  chat:
    prefix: "&8[&f-&8] &f"
    enabledMessage: "You &a&nenabled&r your pvp!"
    enabledByOtherMessage: "Your pvp has been &a&nenabled&r!"
    disabledMessage: "You &c&ndisabled&r your pvp!"
    disabledByOtherMessage: "Your pvp has been &c&ndisabled&r!"
    disabledGraceMessage: "" # "You &ndisabled&r your newbie protection, your PVP is &a&nenabled&r!"
    disabledGraceByOtherMessage: "" # "Your newbie protection has been &ndisabled&r, your PVP is &a&nenabled&r!"
    preventedToggleInWorldsMessage: "&cYou cannot toggle pvp in this world!"
    preventedToggleWithBountyMessage: "&cYou cannot toggle pvp with an active bounty!"
    preventedToggleInCombatMessage: "&cYou cannot toggle pvp during combat!"
    preventedToggleAfterCombatMessage: "&cYou cannot toggle pvp after recent combat -- please wait &6<time_left>&c!"
    preventedToggleAfterMurderMessage: "&cYou cannot toggle pvp after killing someone -- please wait &6<time_left>&c!"
    preventedToggleAfterDeathMessage: "&cYou cannot toggle pvp after recently dying -- please wait &6<time_left>&c!"
    preventedToggleAfterCombatLogMessage: "&cYou cannot toggle pvp after combat-logging -- please wait &6<time_left>&c!"
    preventedToggleAfterJoinMessage: "&cYou cannot toggle pvp after recently connecting -- please wait &6<time_left>&c!"
    preventedToggleAfterEnablingMessage: "&cYou cannot toggle pvp after recently toggling -- please wait &6<time_left>&c!"
    preventedToggleAfterSetBountyMessage: "&cYou cannot toggle pvp after recently setting a bounty -- please wait &6<time_left>&c!"
    preventedToggleAfterBonusMessage: "&cYou cannot toggle pvp -- please wait &6<time_left>&c!"
    forceEnabledAfterMessage: "Your pvp was &are-&nenabled&r!"
  forceEnabledAfterDeath: true
  forceEnabledAfterSetBounty: true
  forceEnabledWorldChangeListener: true
  preventedInWorlds: []
    #- "world_nether"
  preventedWithBounty: true
  preventedInCombat: true
  preventedAfterCombat:
    enabled: true
    time: 30 # seconds
  preventedAfterMurder:
    enabled: true
    time: 600 # seconds
  preventedAfterPVPDeath:
    enabled: true
    time: 120 # seconds
  preventedAfterPVEDeath:
    enabled: true
    time: 120 # seconds
  preventedAfterCombatLog:
    enabled: true
    time: 300 # seconds
  preventedAfterJoin:
    enabled: true
    time: 120 # seconds
  preventedAfterEnable:
    enabled: true
    time: 30 # seconds
  preventedAfterSetBounty:
    enabled: true
    time: 600 # seconds