name: DeluxeCombatAddon64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.deluxecombataddon64.DeluxeCombatAddon64
api-version: 1.17
depend: [DeluxeCombat]
commands:
  pvp:
    description: Base command for DeluxeCombatAddon64's toggle pvp features
  bountyprot:
    description: Base command for DeluxeCombatAddon64's bounty protection feature
permissions:
  deluxecombataddon64.toggle.self:
    description: Ability to toggle your pvp and grace protection with /pvp
    default: true
  deluxecombataddon64.toggle.others:
    description: Ability to toggle others' pvp and grace protection with /pvp
    default: op
  deluxecombataddon64.managecooldowns:
    description: Ability to get/give/clear players' toggle pvp cooldown timers with /pvp
    default: op
  deluxecombataddon64.manageprotections:
    description: Ability to get/set/add/clear players' bounty protection timers with /bountyprot
    default: op