name: DeluxeCombatAddon64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.deluxecombataddon64.DeluxeCombatAddon64
api-version: 1.17
harddepend: [DeluxeCombat]
commands:
  togglepvp:
    description: Base command for DeluxeCombatAddon64
permissions:
  deluxecombataddon64.toggle.self:
    description: Ability to use /togglepvp
    default: true
  deluxecombataddon64.toggle.others:
    description: Ability to use /togglepvp on others
    default: op